spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: admin123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    formcontent:
      filter:
        enabled: true
    hidden-method:
      filter:
        enabled: true